# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simu_prep <- function(ref, tot_len, omit) {
    .Call('_convSig_simu_prep', PACKAGE = 'convSig', ref, tot_len, omit)
}

feat2table3 <- function(b1, b2, b3) {
    .Call('_convSig_feat2table3', PACKAGE = 'convSig', b1, b2, b3)
}

feat2table5 <- function(b1, b2, b3, b4, b5) {
    .Call('_convSig_feat2table5', PACKAGE = 'convSig', b1, b2, b3, b4, b5)
}

reverse_transform <- function(alleles) {
    .Call('_convSig_reverse_transform', PACKAGE = 'convSig', alleles)
}

shallow_loop3 <- function(mat, fasta, mut_file, uniq_samples, chro) {
    .Call('_convSig_shallow_loop3', PACKAGE = 'convSig', mat, fasta, mut_file, uniq_samples, chro)
}

shallow_loop5 <- function(mat, fasta, mut_file, uniq_samples, chro) {
    .Call('_convSig_shallow_loop5', PACKAGE = 'convSig', mat, fasta, mut_file, uniq_samples, chro)
}

conv_bimap <- function(N, numbase) {
    .Call('_convSig_conv_bimap', PACKAGE = 'convSig', N, numbase)
}

RM_nonSNP <- function(startend, ar) {
    .Call('_convSig_RM_nonSNP', PACKAGE = 'convSig', startend, ar)
}

timesTwo <- function(x) {
    .Call('_convSig_timesTwo', PACKAGE = 'convSig', x)
}

timesTwoList <- function(x) {
    .Call('_convSig_timesTwoList', PACKAGE = 'convSig', x)
}

WeirdVector <- function(x) {
    .Call('_convSig_WeirdVector', PACKAGE = 'convSig', x)
}

string_comptest <- function(x) {
    .Call('_convSig_string_comptest', PACKAGE = 'convSig', x)
}

string_comptest2 <- function(x, y, a) {
    .Call('_convSig_string_comptest2', PACKAGE = 'convSig', x, y, a)
}

