# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

reverse_transform <- function(alleles) {
    .Call('_convSig_reverse_transform', PACKAGE = 'convSig', alleles)
}

shallow_loop3 <- function(mat) {
    .Call('_convSig_shallow_loop3', PACKAGE = 'convSig', mat)
}

fasta_process3 <- function(fasta, mut_file) {
    .Call('_convSig_fasta_process3', PACKAGE = 'convSig', fasta, mut_file)
}

RM_nonSNP <- function(startend, ar) {
    .Call('_convSig_RM_nonSNP', PACKAGE = 'convSig', startend, ar)
}

timesTwo <- function(x) {
    .Call('_convSig_timesTwo', PACKAGE = 'convSig', x)
}

timesTwoList <- function(x) {
    .Call('_convSig_timesTwoList', PACKAGE = 'convSig', x)
}

